name: ${name}
main: ${main}
version: ${version}
author: ${author}
api-version: 1.17
folia-supported: true

depend:
  - packetevents

softdepend:
  - PlaceholderAPI
  - TAB

commands:
  nametags-reload:
    description: Raeload the config